server {
    listen 3000;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/auth/ {
        proxy_pass http://host.docker.internal:8080/api/auth/;
    }

    location /api/quiz/ {
        proxy_pass http://host.docker.internal:8081/api/quiz/;
    }

    location /api/flashcard/ {
        proxy_pass http://host.docker.internal:8082/api/flashcard/;
    }
}