server {
    listen 3000;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/quiz/ {
        proxy_pass http://quiz-service:8083;
    }

    location /api/flashcard/ {
        proxy_pass http://flashcard-service:8083;
    }

    location /api/auth/ {   
        proxy_pass http://auth-service:8083;
    }
}
