server {
    listen 3000;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/quiz/ {
        proxy_pass http://${QUIZ_HOST}/api/quiz/;
    }

    location /api/flashcard/ {
        proxy_pass http://${FLASHCARD_HOST}/api/flashcard/;
    }

    location /api/auth/ {
        proxy_pass http://${AUTH_HOST}/api/auth/;
    }
}
