services:
  db:
    image: postgres:14
    container_name: studyapp_db
    restart: always
    env_file:
      - .env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/initdb:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:6.21
    container_name: studyapp_pgadmin
    restart: always
    env_file:
      - .env.prod
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@you.com
      PGADMIN_DEFAULT_PASSWORD: AdminPass123!
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./database/pgadmin4/servers.json:/pgadmin4/servers.json:ro

  quiz-service:
    image: ghcr.io/yuyangc-gh/team-deployaas/quiz-service:latest
    container_name: studyapp_quiz_service
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/initexample
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

  flashcard-service:
    image: ghcr.io/yuyangc-gh/team-deployaas/flashcard-service:latest
    container_name: studyapp_flashcard_service
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/initexample
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

  auth-service:
    image: ghcr.io/yuyangc-gh/team-deployaas/auth-service:latest
    container_name: studyapp_auth_service
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/initexample
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

  client:
    image: ghcr.io/yuyangc-gh/team-deployaas/client:latest
    container_name: studyapp_client
    restart: always
    depends_on:
      - auth-service
      - quiz-service
      - flashcard-service
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL}

volumes:
  pgdata:
