apiVersion: v1
kind: Config
clusters:
- name: "student"
  cluster:
    server: "https://rancher.ase.cit.tum.de/k8s/clusters/c-m-nhcfjg9h"
    insecure-skip-tls-verify: true

users:
- name: "student"
  user:
    token: "token-nf2b2:dn6jbcddpwr2kqnvbb68tpnhgf4zfvgv9dl2j2cbf6qvzwpd6tdnrz"

contexts:
- name: "student"
  context:
    user: "student"
    cluster: "student"

current-context: "student"