{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "study-assistant.fullname" . }}-grafana-datasources
  labels:
    {{- include "study-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ include "study-assistant.fullname" . }}-prometheus:9090
        uid: PBFA97CFB590B2093
        isDefault: true
        editable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "study-assistant.fullname" . }}-grafana-dashboards
  labels:
    {{- include "study-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /etc/grafana/provisioning/dashboards
  study-assistant-dashboard.json: |
{{ .Files.Get "dashboard.json" | indent 4 }}
{{- end }}
