apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "study-assistant.fullname" . }}-nginx-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "study-assistant.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location /api/quiz/ {
            proxy_pass http://{{ include "study-assistant.fullname" . }}-quiz-service:{{ .Values.services.quizService.port }}/api/quiz/;
        }

        location /api/courses {
            proxy_pass http://{{ include "study-assistant.fullname" . }}-quiz-service:{{ .Values.services.quizService.port }}/api/quiz/courses/detailed;
        }

        location /api/flashcard/ {
            proxy_pass http://{{ include "study-assistant.fullname" . }}-flashcard-service:{{ .Values.services.flashcardService.port }}/api/flashcard/;
        }

        location /api/auth/ {
            proxy_pass http://{{ include "study-assistant.fullname" . }}-auth-service:{{ .Values.services.authService.port }}/api/auth/;
        }
    }
