apiVersion: v1
kind: Service
metadata:
  name: {{ include "study-assistant.fullname" . }}-client
  labels:
    {{- include "study-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "study-assistant.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: client
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "study-assistant.fullname" . }}-quiz-service
  labels:
    {{- include "study-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: quiz-service
spec:
  type: {{ .Values.quizService.service.type }}
  ports:
    - port: {{ .Values.quizService.service.port }}
      targetPort: {{ .Values.quizService.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "study-assistant.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: quiz-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "study-assistant.fullname" . }}-flashcard-service
  labels:
    {{- include "study-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: flashcard-service
spec:
  type: {{ .Values.flashcardService.service.type }}
  ports:
    - port: {{ .Values.flashcardService.service.port }}
      targetPort: {{ .Values.flashcardService.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "study-assistant.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: flashcard-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "study-assistant.fullname" . }}-auth-service
  labels:
    {{- include "study-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-service
spec:
  type: {{ .Values.authService.service.type }}
  ports:
    - port: {{ .Values.authService.service.port }}
      targetPort: {{ .Values.authService.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "study-assistant.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: auth-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "study-assistant.fullname" . }}-genai-service
  labels:
    {{- include "study-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: genai-service
spec:
  type: {{ .Values.genaiService.service.type }}
  ports:
    - port: {{ .Values.genaiService.service.port }}
      targetPort: {{ .Values.genaiService.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "study-assistant.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: genai-service
