apiVersion: v1
kind: Config
clusters:
- name: "student"
  cluster:
    server: "https://rancher.ase.cit.tum.de/k8s/clusters/c-m-nhcfjg9h"
    insecure-skip-tls-verify: true

users:
- name: "student"
  user:
    token: "kubeconfig-u-5vmvz66osqxl9lg:2nqwxm75gnxb6mt685bmwg4cxxsnv4fqnqbfjlft29wdbrwqxxvdsp"


contexts:
- name: "student"
  context:
    user: "student"
    cluster: "student"

current-context: "student"
