apiVersion: v1
kind: Config
clusters:
- name: "student"
  cluster:
    server: "https://rancher.ase.cit.tum.de/k8s/clusters/c-m-nhcfjg9h"
    insecure-skip-tls-verify: true

users:
- name: "student"
  user:
    token: "kubeconfig-u-5vmvz66osq47nwr:qdwzfrwdmhjbmj4mmcwgqphvsckmxrbhzjsdskfhq96htdkdxs66hs"


contexts:
- name: "student"
  context:
    user: "student"
    cluster: "student"

current-context: "student"
