---
- name: Install Docker and Docker Compose
  hosts: all
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install required system packages
      yum:
        name:
          - docker
          - python3-pip
        update_cache: true
        state: present

    - name: Install Docker Compose v2 using pip
      pip:
        name: docker-compose
        extra_args: --ignore-installed

    - name: Create directory for Docker CLI plugins
      file:
        path: /usr/libexec/docker/cli-plugins
        state: directory
        mode: '0755'
        recurse: yes

    - name: Install Docker Compose v2 plugin
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64
        dest: /usr/libexec/docker/cli-plugins/docker-compose
        mode: '0755'

    - name: Start Docker daemon
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Install Docker SDK for Python
      pip:
        name:
          - docker

- name: Create new Linux user for deployment
  hosts: all
  become: true
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create new user 'deployuser'
      user:
        name: deployuser
        groups: adm,docker
        append: yes

    - name: Reconnect to server session
      meta: reset_connection

- name: Copy all service directories to remote server
  hosts: all
  become: true
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Copy service directory "{{ item }}"
      copy:
        src: "../../{{ item }}"
        dest: "/home/deployuser/{{ item }}"
        owner: deployuser
        group: deployuser
        mode: '0755'
      loop:
        - auth-service
        - client
        - database
        - flashcard-service
        - quiz-service


- name: Deploy Docker Compose project
  hosts: all
  become: true
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ensure target directory exists and is owned by deployuser
      file:
        path: /home/deployuser
        state: directory
        owner: deployuser
        group: deployuser
        mode: '0755'

    - name: Copy .env file to remote server
      copy:
        src:  ../../.env
        dest: /home/deployuser/.env
        mode: '0644'

    - name: Copy docker-compose.yml to remote server
      copy:
        src: ../../docker-compose.yml
        dest: /home/deployuser/docker-compose.yml
        owner: deployuser
        group: deployuser
        mode: '0644'

    - name: Start Docker container with Compose v2
      community.docker.docker_compose_v2:
        project_src: /home/deployuser
        state: present