package com.aet.studyassistant.quiz_service.model;

import org.junit.jupiter.api.Test;

import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

class QuestionTest {

    private static final String TEST_QUESTION_TEXT = "What is DevOps?";
    private static final String TEST_SAMPLE_SOLUTION = "DevOps is a set of practices that combines software development and IT operations.";
    private static final Integer TEST_ORDERING = 1;
    private static final UUID TEST_QUESTION_ID = UUID.randomUUID();
    private static final UUID TEST_COURSE_ID = UUID.randomUUID();
    private static final String TEST_CHAPTER_NAME = "Test Chapter Name";

    @Test
    void defaultConstructorCreatesValidQuestion() {
        // Arrange & Act
        Question question = new Question();

        // Assert
        assertNull(question.getId());
        assertNull(question.getText());
        assertNull(question.getSampleSolution());
        assertNull(question.getOrdering());
        assertNull(question.getChapter());
    }

    @Test
    void parameterizedConstructorCreatesCorrectQuestion() {
        // Arrange
        Chapter chapter = new Chapter(TEST_CHAPTER_NAME, TEST_COURSE_ID);

        // Act
        Question question = new Question(TEST_QUESTION_TEXT, TEST_SAMPLE_SOLUTION, TEST_ORDERING, chapter);

        // Assert
        assertNull(question.getId()); // ID is generated by JPA
        assertEquals(TEST_QUESTION_TEXT, question.getText());
        assertEquals(TEST_SAMPLE_SOLUTION, question.getSampleSolution());
        assertEquals(TEST_ORDERING, question.getOrdering());
        assertEquals(chapter, question.getChapter());
    }

    @Test
    void settersUpdateFieldsCorrectly() {
        // Arrange
        Question question = new Question();
        Chapter chapter = new Chapter(TEST_CHAPTER_NAME, TEST_COURSE_ID);

        // Act
        question.setId(TEST_QUESTION_ID);
        question.setText(TEST_QUESTION_TEXT);
        question.setSampleSolution(TEST_SAMPLE_SOLUTION);
        question.setOrdering(TEST_ORDERING);
        question.setChapter(chapter);

        // Assert
        assertEquals(TEST_QUESTION_ID, question.getId());
        assertEquals(TEST_QUESTION_TEXT, question.getText());
        assertEquals(TEST_SAMPLE_SOLUTION, question.getSampleSolution());
        assertEquals(TEST_ORDERING, question.getOrdering());
        assertEquals(chapter, question.getChapter());
    }

    @Test
    void gettersReturnCorrectValues() {
        // Arrange
        Chapter chapter = new Chapter(TEST_CHAPTER_NAME, TEST_COURSE_ID);
        Question question = new Question(TEST_QUESTION_TEXT, TEST_SAMPLE_SOLUTION, TEST_ORDERING, chapter);
        question.setId(TEST_QUESTION_ID);

        // Act & Assert
        assertEquals(TEST_QUESTION_ID, question.getId());
        assertEquals(TEST_QUESTION_TEXT, question.getText());
        assertEquals(TEST_SAMPLE_SOLUTION, question.getSampleSolution());
        assertEquals(TEST_ORDERING, question.getOrdering());
        assertEquals(chapter, question.getChapter());
    }

    @Test
    void questionHandlesNullText() {
        // Arrange
        Chapter chapter = new Chapter(TEST_CHAPTER_NAME, TEST_COURSE_ID);

        // Act
        Question question = new Question(null, TEST_SAMPLE_SOLUTION, TEST_ORDERING, chapter);

        // Assert
        assertNull(question.getText());
        assertEquals(TEST_SAMPLE_SOLUTION, question.getSampleSolution());
        assertEquals(TEST_ORDERING, question.getOrdering());
        assertEquals(chapter, question.getChapter());
    }

    @Test
    void questionHandlesNullSampleSolution() {
        // Arrange
        Chapter chapter = new Chapter(TEST_CHAPTER_NAME, TEST_COURSE_ID);

        // Act
        Question question = new Question(TEST_QUESTION_TEXT, null, TEST_ORDERING, chapter);

        // Assert
        assertEquals(TEST_QUESTION_TEXT, question.getText());
        assertNull(question.getSampleSolution());
        assertEquals(TEST_ORDERING, question.getOrdering());
        assertEquals(chapter, question.getChapter());
    }

    @Test
    void questionHandlesNullOrdering() {
        // Arrange
        Chapter chapter = new Chapter(TEST_CHAPTER_NAME, TEST_COURSE_ID);

        // Act
        Question question = new Question(TEST_QUESTION_TEXT, TEST_SAMPLE_SOLUTION, null, chapter);

        // Assert
        assertEquals(TEST_QUESTION_TEXT, question.getText());
        assertEquals(TEST_SAMPLE_SOLUTION, question.getSampleSolution());
        assertNull(question.getOrdering());
        assertEquals(chapter, question.getChapter());
    }

    @Test
    void questionHandlesNullChapter() {
        // Arrange & Act
        Question question = new Question(TEST_QUESTION_TEXT, TEST_SAMPLE_SOLUTION, TEST_ORDERING, null);

        // Assert
        assertEquals(TEST_QUESTION_TEXT, question.getText());
        assertEquals(TEST_SAMPLE_SOLUTION, question.getSampleSolution());
        assertEquals(TEST_ORDERING, question.getOrdering());
        assertNull(question.getChapter());
    }

    @Test
    void questionHandlesEmptyText() {
        // Arrange
        String emptyText = "";
        Chapter chapter = new Chapter(TEST_CHAPTER_NAME, TEST_COURSE_ID);

        // Act
        Question question = new Question(emptyText, TEST_SAMPLE_SOLUTION, TEST_ORDERING, chapter);

        // Assert
        assertEquals(emptyText, question.getText());
    }

    @Test
    void questionHandlesEmptySampleSolution() {
        // Arrange
        String emptySolution = "";
        Chapter chapter = new Chapter(TEST_CHAPTER_NAME, TEST_COURSE_ID);

        // Act
        Question question = new Question(TEST_QUESTION_TEXT, emptySolution, TEST_ORDERING, chapter);

        // Assert
        assertEquals(emptySolution, question.getSampleSolution());
    }

    @Test
    void questionHandlesZeroOrdering() {
        // Arrange
        Integer zeroOrdering = 0;
        Chapter chapter = new Chapter(TEST_CHAPTER_NAME, TEST_COURSE_ID);

        // Act
        Question question = new Question(TEST_QUESTION_TEXT, TEST_SAMPLE_SOLUTION, zeroOrdering, chapter);

        // Assert
        assertEquals(zeroOrdering, question.getOrdering());
    }

    @Test
    void questionHandlesNegativeOrdering() {
        // Arrange
        Integer negativeOrdering = -1;
        Chapter chapter = new Chapter(TEST_CHAPTER_NAME, TEST_COURSE_ID);

        // Act
        Question question = new Question(TEST_QUESTION_TEXT, TEST_SAMPLE_SOLUTION, negativeOrdering, chapter);

        // Assert
        assertEquals(negativeOrdering, question.getOrdering());
    }

    @Test
    void questionHandlesAllNullParameters() {
        // Arrange & Act
        Question question = new Question(null, null, null, null);

        // Assert
        assertNull(question.getText());
        assertNull(question.getSampleSolution());
        assertNull(question.getOrdering());
        assertNull(question.getChapter());
    }
}
