server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/quiz/ {
        proxy_pass http://study-assistant-quiz-service:8081/api/quiz/;
    }

    location /api/courses {
        proxy_pass http://study-assistant-quiz-service:8081/api/quiz/courses/detailed;
    }

    location /api/flashcard/ {
        proxy_pass http://study-assistant-flashcard-service:8082/api/flashcard/;
    }

    location /api/auth/ {
        proxy_pass http://study-assistant-auth-service:8083/api/auth/;
    }

    location /api/genai/ {
        proxy_pass http://study-assistant-genai-service:5001/;
    }
}
